--PREGUNTA 5

--Empleados
SELECT V.VUELO_ID, AENTRADA.NOMBRE, ASALIDA.NOMBRE, TO_CHAR(V.FECHA_HORA_PARTIDA, 'DD.MM.YYYY HH24:MI'), TO_CHAR(V.FECHA_HORA_LLEGADA, 'DD.MM.YYYY HH24:MI'), E.NRO_DOCUMENTO, E.NOMBRES, E.AP_PATERNO, C.DETALLE_CARGO   
FROM AP_VUELOS V, AP_EMPLEADOS_VUELOS VU, AP_EMPLEADOS E, AP_CARGOS C,
    AP_AEROPUERTOS AENTRADA, AP_AEROPUERTOS ASALIDA

WHERE V.VUELO_ID = VU.VUELO_ID AND VU.EMPLEADO_ID = E.EMPLEADO_ID AND E.CARGO_ID = C.CARGO_ID 
    AND V.AEROPUERTO_PARTIDA_ID = AENTRADA.AEROPUERTO_ID AND V.AEROPUERTO_LLEGADA_ID = ASALIDA.AEROPUERTO_ID
    --AND E.ACTIVO = 1 --No se menciona que esten activos, además en el ejemplo no lo muestran con activos


UNION --Union sin repiticion, si diria repetidos seria UNION ALL pero no es el caso

--Pasajeros
SELECT V.VUELO_ID, AENTRADA.NOMBRE, ASALIDA.NOMBRE, TO_CHAR(V.FECHA_HORA_PARTIDA, 'DD.MM.YYYY HH24:MI'), TO_CHAR(V.FECHA_HORA_LLEGADA, 'DD.MM.YYYY HH24:MI'), P.NRO_DOCUMENTO, P.NOMBRES, P.AP_PATERNO, 'Pasajero' 
FROM AP_VUELOS V, AP_BOLETOS BO, AP_PASAJEROS P,
    AP_AEROPUERTOS AENTRADA, AP_AEROPUERTOS ASALIDA
WHERE V.VUELO_ID = BO.VUELO_ID AND BO.PASAJERO_ID = P.PASAJERO_ID
    AND V.AEROPUERTO_PARTIDA_ID = AENTRADA.AEROPUERTO_ID AND V.AEROPUERTO_LLEGADA_ID = ASALIDA.AEROPUERTO_ID
    
ORDER BY VUELO_ID --No lo menciona pero por si acaso xd, aunque de hecho no está ordenado por esto

--Para el formato de la hora lo considere como horas:minutos, 